### ISSUE TITLE
Issue importing ligo.skymap

### ISSUE THREAD

**Issue by yusuf2310** [lpsinger/ligo.skymap#16]
Hi! I used "pip install ligo.skymap", I've tried updating NumPy as suggested in a similar issue before, but I still get the error below.
I'm using Python 3.9.7 on JupyterLab, my computer's Dell XPS 9360, Windows 10 Home v.21H2. Could you help me resolve this?
```
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_28660/2355149721.py in <module>
----> 1 import ligo.skymap

ModuleNotFoundError: No module named 'ligo'
```

**Comment by lpsinger** [comment]
Are you using Windows Subsystem for Linux? ligo.skymap does not support native Windows installations.

**Comment by CriticallyUncertain** [comment]
Is installing from source the way to go, as described here: https://lscsoft.docs.ligo.org/ligo.skymap/develop.html?

**Comment by lpsinger** [comment]
Would you please try installing in a fresh virtual environment using [venv](https://docs.python.org/3/library/venv.html), [virtualenv](https://virtualenv.pypa.io/en/latest/), or their equivalent, and post all commands and output?

**Comment by lpsinger** [comment]
> Is installing from source the way to go, as described here: https://lscsoft.docs.ligo.org/ligo.skymap/develop.html?

No. If you are installing on WSL, then the prebuilt wheels should be fine.

**Comment by lpsinger** [comment]
A thought: if you are following the development instructions, then try cd'ing to a directory other than the source checkout directory, then try importing.

**Comment by CriticallyUncertain** [comment]
> Would you please try installing in a fresh virtual environment using [venv](https://docs.python.org/3/library/venv.html), [virtualenv](https://virtualenv.pypa.io/en/latest/), or their equivalent, and post all commands and output?

```
C:\Users\crit>python -m pip install --user virtualenv
Error processing line 1 of C:\Users\crit\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib-3.4.3-py3.9-nspkg.pth:

  Traceback (most recent call last):
    File "C:\Users\crit\AppData\Local\Programs\Python\Python39\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 562, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
Collecting virtualenv
  Downloading virtualenv-20.16.5-py3-none-any.whl (8.8 MB)
     ---------------------------------------- 8.8/8.8 MB 19.4 MB/s eta 0:00:00
Collecting filelock<4,>=3.4.1
  Downloading filelock-3.8.0-py3-none-any.whl (10 kB)
Collecting platformdirs<3,>=2.4
  Downloading platformdirs-2.5.2-py3-none-any.whl (14 kB)
Collecting distlib<1,>=0.3.5
  Downloading distlib-0.3.6-py2.py3-none-any.whl (468 kB)
     ---------------------------------------- 468.5/468.5 kB 28.6 MB/s eta 0:00:00
Installing collected packages: distlib, platformdirs, filelock, virtualenv
  WARNING: The script virtualenv.exe is installed in 'C:\Users\crit\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed distlib-0.3.6 filelock-3.8.0 platformdirs-2.5.2 virtualenv-20.16.5
```

**Comment by lpsinger** [comment]
OK, now you have virtualenv installed. Now please try creating a virtual environment and installing ligo.skymap inside of it.

**Comment by CriticallyUncertain** [comment]
Sorry for taking much time, this is a bit new to me. 
I created a virtual environment "env" and installed ligo.skymap. I see some error messages.

```
(env) C:\Users\yusuf>py -m pip install ligo.skymap
Collecting ligo.skymap
  Using cached ligo.skymap-1.0.2.tar.gz (2.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached ligo.skymap-1.0.1.tar.gz (2.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached ligo.skymap-1.0.0.tar.gz (2.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached ligo.skymap-0.6.1.tar.gz (2.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached ligo.skymap-0.6.0.tar.gz (2.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting ligo-segments>=1.2.0
  Using cached ligo-segments-1.4.0.tar.gz (51 kB)
  Preparing metadata (setup.py) ... done
Collecting ligo-gracedb>=2.0.1
  Using cached ligo_gracedb-2.8.0-py2.py3-none-any.whl (2.3 MB)
Collecting numpy>=1.19.3
  Using cached numpy-1.23.3-cp39-cp39-win_amd64.whl (14.7 MB)
Collecting pillow>=2.5.0
  Downloading Pillow-9.2.0-cp39-cp39-win_amd64.whl (3.3 MB)
     ---------------------------------------- 3.3/3.3 MB 13.1 MB/s eta 0:00:00
Collecting matplotlib>=3.4.0
  Downloading matplotlib-3.6.0-cp39-cp39-win_amd64.whl (7.2 MB)
     ---------------------------------------- 7.2/7.2 MB 24.2 MB/s eta 0:00:00
Collecting astropy>=5.0
  Using cached astropy-5.1-cp39-cp39-win_amd64.whl (6.5 MB)
Collecting ptemcee
  Using cached ptemcee-1.0.0.tar.gz (17 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\yusuf\AppData\Local\Temp\pip-install-72acgrc0\ptemcee_b118fed39f1f42beb15df7baab91256f\setup.py", line 39, in <module>
          long_description=read('README.rst'),
        File "C:\Users\yusuf\AppData\Local\Temp\pip-install-72acgrc0\ptemcee_b118fed39f1f42beb15df7baab91256f\setup.py", line 20, in read
          return f.read()
        File "C:\Users\yusuf\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 449: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by lpsinger** [comment]
Ah, this is an issue with one of ligo.skymap's dependencies. See willvousden/ptemcee#11.
